import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReCaptchaProvider } from "next-recaptcha-v3";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Params = Promise<{ locale: string }>;

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Params
}) {

  const { locale } = await params

  const messages = await getMessages({ locale: locale });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReCaptchaProvider reCaptchaKey={process.env.NEXT_PUBLIC_G_RECAPTCHA_PUBLIC} language={locale}>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
